services:
  postgres:
    image: postgres:18-alpine
    container_name: dream_theater_postgres
    environment:
      POSTGRES_DB: dream_theater
      POSTGRES_USER: vasch3nko
      POSTGRES_PASSWORD: zubizubi
    ports:
      - "5432:5432"
    volumes:
      - dream_theater_postgres_dev_data:/var/lib/postgresql/data
    networks:
      - dream_theater_network

volumes:
  dream_theater_postgres_dev_data:

networks:
  dream_theater_network:
    driver: bridge
